### PR TITLE
Update video.js to latest 4.1.0 version

### PR DESCRIPTION
**Pull request by justinmayer**
The video.js project has progressed significantly since the 3.1.0 version that the initial 0.1 release of this plugin bundled. This PR updates the plugin to include the most recent version of video.js.

### CODE REVIEW

**Comment by beniwohli** [comment]
Hey, thanks for your contribution! I don't use this plugin currently in any productive set up, so I can't really test it. I guess you tested the changes before submitting the PR?

**Comment by justinmayer** [comment]
We are using this in staging, and it's going into production within 2-3 weeks.

There will be some additional changes forthcoming in order to properly support Flash fallback. Given that you're not using this plugin in production, do you want to continue maintaining this repo, or should we take it over? Either way is fine with us.  :)

**Comment by beniwohli** [comment]
@justinmayer sure, I'll gladly hand it over to you, thanks for the offer :) I'll get in touch with github so that they mark your repo as the main repo. What's your username on pypi?

**Comment by justinmayer** [comment]
On Jul 18, 2013, at 4:39 AM, Benjamin Wohlwend notifications@github.com wrote:

> @justinmayer sure, I'll gladly hand it over to you, thanks for the offer :) I'll get in touch with github so that they mark your repo as the main repo.
> 
> That sounds great. Thanks, Benjamin!
> What's your username on pypi?

My username on PyPI is:  jmayer

Thanks again, Benjamin. We have a few more improvements in store.  :^)

**Comment by justinmayer** [comment]
@piquadrat: Just following up on this. Did you ever take the appropriate steps with GitHub and PyPI? There's an outstanding pull request on my fork, so it would be great if you could help us out.  (^_^)

**Pull request closed without merging**
